version: "3.8"

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  ollama:
