services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - 8501:8501
    volumes:
      - .:/app
      - /app/.venv
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
